spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    console.path: /h2-console
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

setup:
  file:
    name: 'employee-data.txt'